spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jfun?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    isRedisCache: 1 #1开启session缓存
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  cache:
    ehcache:
      config: config/ehcache.xml

server:
  tomcat:
    uri-encoding: UTF-8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.xiejx.jfun.entity
